# safelist
branches:
  only:
  - master

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # udagram-feed-service
  - export CONFIG=joachimloge/udagram-feed-service
  - docker build -t udagram-feed-service ./udagram-api/feed-service
  - docker tag joachimloge/udagram-feed-service:latest
  - docker push joachimloge/udagram-feed-service:latest  

  # udagram-user-service
  - export CONFIG=joachimloge/udagram-user-service
  - docker build -t udagram-user-service ./udagram-api/user-service
  - docker tag joachimloge/udagram-user-service:latest
  - docker push joachimloge/udagram-user-service:latest 

  # udagram-api-gateway
  - export CONFIG=joachimloge/udagram-api-gateway
  - docker build -t udagram-api-gateway ./udagram-api-gateway
  - docker tag joachimloge/udagram-api-gateway:latest
  - docker push joachimloge/udagram-api-gateway:latest 