version: '3.7'
services:
  udagram-frontend:
    container_name: udagram-frontend
    build: udagram-frontend
    networks:
      - udagram-service-network       
    ports:
      - "8100:80"

  user-service:
    container_name: udagram-user-service
    build: udagram-api/user-service
#    image: udagram-user-service
    ports:
    - 8081:8081
    networks:
      - udagram-service-network
    environment:
      - UDACITY_DB_USERNAME=${UDACITY_DB_USERNAME}
      - UDACITY_DB_PASSWORD=${UDACITY_DB_PASSWORD}
      - UDACITY_DB_DATABASE=${UDACITY_DB_DATABASE}
      - UDACITY_DB_HOST=${UDACITY_DB_HOST}
      - AWS_REGION=${AWS_REGION}
      - AWS_PROFILE=${AWS_PROFILE}
      - UDACITY_AWS_MEDIA_BUCKET=${UDACITY_AWS_MEDIA_BUCKET}
      - UDACITY_JWT=${UDACITY_JWT}

  feed-service:
    container_name: udagram-feed-service
    build: udagram-api/feed-service
#    image: udagram-feed-service
    ports:
    - 8082:8082
    networks:
      - udagram-service-network
    environment:
      - UDACITY_DB_USERNAME=${UDACITY_DB_USERNAME}
      - UDACITY_DB_PASSWORD=${UDACITY_DB_PASSWORD}
      - UDACITY_DB_DATABASE=${UDACITY_DB_DATABASE}
      - UDACITY_DB_HOST=${UDACITY_DB_HOST}
      - AWS_REGION=${AWS_REGION}
      - AWS_PROFILE=${AWS_PROFILE}
      - UDACITY_AWS_MEDIA_BUCKET=${UDACITY_AWS_MEDIA_BUCKET}
      - UDACITY_JWT=${UDACITY_JWT}


  api-gateway:
    container_name: udagram-api-gateway
    build: udagram-api-gateway
#    image: udagram-api-gateway
    ports:
    - 8080:8080
    networks:
      - udagram-service-network

networks:
  udagram-service-network:
    name: udagram-service-network
    driver: "bridge"
